// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOvmdDfo0dPIwDKjL9rmeQ7mNx34AbvR0',
    appId: '1:919362131099:web:17dbeb536320a266dee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    authDomain: 'fir-series-2d91e.firebaseapp.com',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
    measurementId: 'G-Y9E1LP1N2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZhF5fPqSpK8cFi15ZiyHcgvusQyZ4yEY',
    appId: '1:919362131099:android:2195aa1b005013b8dee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUxTAskhz7rctqCBfVUYRbYNOyyB2F7s',
    appId: '1:919362131099:ios:b514f7f67642d30fdee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSeries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUxTAskhz7rctqCBfVUYRbYNOyyB2F7s',
    appId: '1:919362131099:ios:b514f7f67642d30fdee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSeries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOvmdDfo0dPIwDKjL9rmeQ7mNx34AbvR0',
    appId: '1:919362131099:web:e9976f8e63acfc03dee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    authDomain: 'fir-series-2d91e.firebaseapp.com',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
    measurementId: 'G-SPW6EZMKSK',
  );
}
